### ISSUE TITLE
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: vkCreateMacOSSurfaceMVK(): On-screen rendering requires a layer of type CAMetalLayer

### ISSUE THREAD

**Issue by nathanfdunn** [Ralith/hypermine#65]
When I run the client I receive the error `[mvk-error] VK_ERROR_INITIALIZATION_FAILED: vkCreateMacOSSurfaceMVK(): On-screen rendering requires a layer of type CAMetalLayer`

I am running macOS 10.15.3

Full stack trace is:
```
$ cargo run --bin client
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/client`
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: vkCreateMacOSSurfaceMVK(): On-screen rendering requires a layer of type CAMetalLayer.
Apr 12 12:53:02.559 ERROR vulkan: VK_ERROR_INITIALIZATION_FAILED: vkCreateMacOSSurfaceMVK(): On-screen rendering requires a layer of type CAMetalLayer. id= number=0 queue_labels= cmd_labels= objects=SURFACE_KHR 7fdf786d9550
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_INITIALIZATION_FAILED', client/src/graphics/window.rs:57:13
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::try::do_call
   7: std::panicking::begin_panic
   8: std::panicking::begin_panic
   9: core::result::Result<T,E>::unwrap
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:963
  10: client::graphics::window::Window::new
             at client/src/graphics/window.rs:57
  11: client::main
             at client/src/main.rs:68
  12: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  13: std::panicking::try::do_call
  14: panic_unwind::dwarf::eh::read_encoded_pointer
  15: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
  16: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  17: client::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Before I got this error, I was receiving `LibraryLoadError("dlopen(libvulkan.dylib, 1): image not found")` which was resolved by installing the latest Vulkan SDK (1.2.135.0) from https://vulkan.lunarg.com/sdk/home. So I think it's possible I'm using the wrong version of Vulkan.

**Comment by Ralith** [comment]
Thanks for the detailed report! This is a bug in one of hypermine's dependencies. I've written up the details at https://github.com/norse-rs/ash-window/issues/8. I'm not sure I can fix this myself as I don't have access to macos for testing, but it should be a simple fix for someone who does.

**Comment by Ralith** [comment]
The current macos-test branch contains an experimental fix; testing reports would be helpful.

**Comment by nathanfdunn** [comment]
No crash now, but I'm getting just a solid blue screen

![image](https://user-images.githubusercontent.com/4128781/80659147-17d6e000-8a56-11ea-8f56-e460a04fff91.png)

**Comment by Ralith** [comment]
Seems like the windowing stuff is working, then; that's the fog color being rendered correctly, but for some reason terrain isn't showing up. Are there any errors in the terminal? Not sure if they show up by default, setting `RUST_LOG=client=trace` in the environment will get you maximum verbosity.

**Comment by nathanfdunn** [comment]
I don't see any errors. After about a minute or two this is what the log shows. Nothing more is logged after several more minutes.

```
$ cargo run --bin client --release
    Finished release [optimized] target(s) in 0.16s
     Running `target/release/client`
Apr 29 20:27:09.732  INFO /Users/default/Library/Preferences/hypermine/client.toml not found, using defaults
Apr 29 20:27:09.858  INFO selected device name="Intel Iris Graphics"
Apr 29 20:27:09.883 TRACE wrote pipeline cache len=8081
Apr 29 20:27:11.213 TRACE adding nodes count=3686
Apr 29 20:27:11.391 TRACE spawning entity id=80e2adf23a688d07
Apr 29 20:27:11.391 TRACE adding nodes count=1625
Apr 29 20:27:11.490 TRACE loading layer=0 path=/Users/default/Projects/hypermine/assets/materials/00000_stone.png
Apr 29 20:27:11.491 TRACE loading layer=1 path=/Users/default/Projects/hypermine/assets/materials/00001_dirt.png
Apr 29 20:27:11.491 TRACE loading layer=2 path=/Users/default/Projects/hypermine/assets/materials/00002_sand.png
Apr 29 20:27:11.492 TRACE loading layer=3 path=/Users/default/Projects/hypermine/assets/materials/00003_trunk_side.png
Apr 29 20:27:11.492 TRACE loading layer=4 path=/Users/default/Projects/hypermine/assets/materials/00004_leaves.png
Apr 29 20:27:11.493 TRACE loading layer=5 path=/Users/default/Projects/hypermine/assets/materials/00005_water.png
Apr 29 20:27:11.493 TRACE loading layer=6 path=/Users/default/Projects/hypermine/assets/materials/00006_snow.png
Apr 29 20:27:11.494 TRACE loading layer=7 path=/Users/default/Projects/hypermine/assets/materials/00007_grass_top.png
Apr 29 20:27:11.494 TRACE loading layer=8 path=/Users/default/Projects/hypermine/assets/materials/00008_redsand.png
Apr 29 20:27:11.495 TRACE loading layer=9 path=/Users/default/Projects/hypermine/assets/materials/00009_redstone.png
Apr 29 20:27:11.496 TRACE loading layer=10 path=/Users/default/Projects/hypermine/assets/materials/00010_valite.png
Apr 29 20:27:11.496 TRACE loading layer=11 path=/Users/default/Projects/hypermine/assets/materials/00011_greystone.png
Apr 29 20:27:11.497 TRACE loading layer=12 path=/Users/default/Projects/hypermine/assets/materials/00012_flower_grass.png
Apr 29 20:27:11.498 TRACE loading layer=13 path=/Users/default/Projects/hypermine/assets/materials/00013_gravel_stone.png
Apr 29 20:27:11.499 TRACE loading layer=14 path=/Users/default/Projects/hypermine/assets/materials/00014_gravel_dirt.png
Apr 29 20:27:11.499 TRACE loading layer=15 path=/Users/default/Projects/hypermine/assets/materials/00015_blackstone.png
Apr 29 20:27:11.500 TRACE loading layer=16 path=/Users/default/Projects/hypermine/assets/materials/00016_big_flower_grass.png
Apr 29 20:27:11.534 TRACE loaded array width=128 height=128 path=/Users/default/Projects/hypermine/assets/materials```

**Comment by Ralith** [comment]
Looks like it's doing what it's supposed to, then. My best guess at this point is that we're hitting a MoltenVK bug (I've had issues with that before, it tends to fall over as soon as you do something fancy); someone equipped for macos graphics debugging would have to investigate further.
